### ISSUE TITLE
sphinx_version_ref does not format well in admonition boxes. 

### ISSUE THREAD

**Issue by wabernat** [max-sn/sphinx_version_ref#1]
I'm using (and pretty happy with) the sphinx_version_ref extension. I hope you can find time to fix this. 

Here's the rst: 

```
#. Enter your Instance ID and your instance's name, then click **Submit                                                                           
   Now!**

   |image3|

   .. tip::

      To find your Instance ID, use the :ref:`kubectl commands                                                                                    
      <get_instance_id>` in the :version-ref:`Install Zenko                                                                                       
      <https://documentation.scality.com/Zenko/{version}/installation/install/Install_Zenko.html>`                                                
      section of :version-ref:`Zenko Installation                                                                                                 
      <https://documentation.scality.com/Zenko/{version}/installation/install/index.html>`.
```

The output looks like: 

![image](https://user-images.githubusercontent.com/35813912/67251052-8b05f680-f422-11e9-992c-8676bf5c79d0.png)

In other words, I think for some reason sphinx is adding a newline (``<p></p>`` in the html) at the end of version-ref tags. You can compare to a conventional :ref: tag in the first link. 

I'm pretty sure I'm doing everything "right" by all the involved tools, but do fee free to set me straight. If you can't maintain this extension for edge cases such as this (I understand you  did it more or less as a lark, and I'm not able to pay), please let me know so I can work around it.

**Comment by wabernat** [comment]
On further study, I see this same behavior outside the admonition box as well. I'll keep digging.

**Comment by max-sn** [comment]
Hi William, thanks for the heads-up and sorry for taking so long to react. I tried your code in the docs of this package (with the `sphinx_rtd_theme`) and I can't seem to reproduce your output. Could you tell me what theme you use?

**Comment by wabernat** [comment]
Max: Thank you so very much for responding!

I am a bit abashed to find that I can no longer reproduce the issue either. I must assume there was a misconfiguration in conf.py that has since been resolved, or perhaps some idiopathic computer issue that remedied itself on a reboot. 

Close the ticket. Sorry to waste your time. If it comes up again, I think I should be able to remember the ticket number.
